apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/naveenvkc/order-service/k8s?ref=main

patches:
- path: patch-env.yml
  
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: order-config
    
images:
- name: order-service
  newName: ghcr.io/naveenvkc/order-service
  newTag: latest

    
replicas:
- count: 1
  name: order-service
